set_statuses_to_finished_auctions:
  every:
    - "60s"
    - :first_in: '10s'
  class: "StatusSetterJob"
  queue: 'status_setter_queue'
  description: "This job sets the status to finished for auctions with exceeded duration. Also sends emails."