check_auctions_status:
  every:
    - "60s"
    - :first_in: '10s'
  class: "AuctionStatusCheckerJob"
  queue: 'status_checker_queue'
  description: "This job checks auctions end time and finalizes them."